import "./globals.css";
import { fontCabinet } from "@/helpers/fontCabinet";
import * as C from "@/components";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${fontCabinet.variable}`}>
        <C.Navbar />
        {children}
      </body>
    </html>
  );
}
