import "./globals.css";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import Head from "next/head";
import { fontCabinet } from "@/helpers/fontCabinet";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${fontCabinet.variable}`}>{children}</body>
    </html>
  );
}
